export const ROUTES = {
  base: "/",
  login: "/login",
  register: "/sign-up",
  home: "/home",
  about: "/about",
  contact: "/contact",
  adminDashboard: "/admin-dashboard",
  adminLogin: "/admin-login",
  adminAddProduct: "/admin-dashboard/admin-add-product",
  adminProductsList: "/admin-dashboard/admin-all-products",
  adminOrderList: "/admin-dashboard/admin-order-list",
  productDetails: "/product-details",
  cart: "/cart",
};
